name: ami-imputation-benchmark
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - scanpy=1.9.5
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - ipykernel
  - requests
  - pip
  - pip:
      - fancyimpute
      - magic-impute
      - scvi-tools
      - GEOparse
